version: '3.9'

services:

  db:
    image: postgres:14.4-alpine
    env_file:
      - .env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend_nw


volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge